
services:
  database:
    image: postgres:alpine
    environment:
      POSTGRES_DB: moonvpn-api
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    networks:
      - moonvpn_network

  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: root
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - moonvpn_network

volumes:
  database_data:

networks:
  moonvpn_network:
    driver: bridge