
services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "8000:8000"
    networks:
      - application_network
    depends_on:
      - mysql
      - rabbitmq

  mysql:
    image: mariadb:10.11.2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: moonvpn-api
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - "application_database:/var/lib/mysql"
    networks:
      - application_network
    ports:
      - "3306:3306"

  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: root
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - application_network

volumes:
  application_database:

networks:
  application_network:
    driver: bridge